### ISSUE TITLE
Loader failed to launch game.exe

### ISSUE THREAD

**Issue by unmd101** [SyndromeDayna/diablo-2-median-xl-sigma-loader#1]
I've put sigma-loader into the game directory but it can't fint the appropriate executable to lauch, I believe. I have 2 executables: "Game.exe" and "Diablo II.exe" and I've tried to rename them to "game.exe" but it doesn't fix the issue.
Wine version: Staging 4.20

**Comment by SyndromeDayna** [comment]
did you solve your problem?

**Comment by SyndromeDayna** [comment]
I have updated the loader to display error codes. If you still have issues then download new version and test.
